### PR TITLE
Merge changes from collaboration-readme-file into main

### PR DESCRIPTION
**Pull request by malakbattat**
I've added the group norms lists, and summaries and i want teammates/ a teammate to review them and merge them

### CODE REVIEW

**Review by abdoalsir — COMMENTED** [review]
I liked all the points added, I have some suggestions for more points to be added like:

We respect agreed timelines to ensure progress and accountability, to ensure adherence to the deadlines
Every team member is encouraged to actively participate and share their perspective during discussions, to ensure everyone contributes to the project
We celebrate all our achievements and have fun doing the work
Feel free to add, adjust or remove any of the points above

**Comment by MuhannadGTR** [comment]
Hello Team 

Collaboration is all about bringing different strengths together. When we work as a team, everyone’s unique perspective and skills help us tackle challenges in ways we couldn’t do alone. It’s about trusting each other, communicating openly, and staying focused on the same goal. When we all pull together and support one another, the results can be amazing!

How does that sound? Would you like any changes?😊

**Comment by MaRia19280** [comment]
The group norms are very well presented and clearly explained.Great job ensuring the norms cover all key aspects of teamwork!

**Comment by MaherAssaf19** [comment]
Hello Team,
Collaboration is about combining our individual strengths to achieve more together. Each person’s unique perspective and skills enable us to overcome challenges in ways we couldn’t on our own. It’s all about building trust, maintaining open communication, and staying aligned toward a shared goal. When we unite and support one another, the outcomes can be truly remarkable!

What do you think? Let me know if you’d like to tweak anything. 💡

**Pull request merged**
